### PR TITLE
Added an example for tunnel junction.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by itdaniher** [comment]
@KOLANICH I'd like to add you to the README as a contributor, could you email itdaniher at gmail dot com your preferred name / identity?

**Comment by KOLANICH** [comment]
22 января 2017 г. 19:39:39 GMT+03:00, Ian Daniher <notifications@github.com> пишет:
>@KOLANICH I'd like to add you to the README as a contributor, could you
>email itdaniher at gmail dot com your preferred name / identity?

My preferred name is KOLANICH. It is my nickname :). My names from passport don't matter, the Internet knows me by nickname. Though my email and all passport (a passport is a book having the same (and a bit more) info than an ID card has) data are easily available for the ones who really need them (you know, there are websites selling leaked government dbs), I ask you not to put my them in your file. I don't want people remember me by passport names.

BTW, why do you need that file? Git commits have authorship info and gh and some other git hosting engines have tools to see contributions in an aggregated way, auto-updated, always relevant. There are also third-party tools like openhub

**Comment by itdaniher** [comment]
I'll be glad to add you as KOLANICH! I asked for your preferred name / identity, KOLANICH is just fine with me.

Just wanted to offer you the option to put your info as several other contributors have chosen to do so.

Thanks for your work!

**Comment by itdaniher** [comment]
@KOLANICH https://github.com/ahkab/ahkab/blob/master/README.md#credits look good?

**Comment by KOLANICH** [comment]
@itdaniher it's OK. Thank you.

**Pull request merged**
